language: android
jdk: oraclejdk8
android:
  components:
      - platform-tools
      - build-tools-25.0.3
      - android-25
      - extra-android-m2repository
script:
     - ./gradlew build jacocoTestReport
before_install:
    - chmod +x gradlew
branches:
  only:
    - master
install: true
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 83fde2f5-6adc-4169-a919-18164acfb997